application: ran-smart-frame
version: 1
runtime: go
api_version: go1

handlers:

- url: /app
  static_dir: app

- url: /app/index\.html
  static_files: app/index.html
  upload: app/index.html

- url: /.*
  script: _go_app
